const day1 = [];
const title = 'Day1 (5/31/16)';
day1.push(title);
day1.push('As the airplane descended I had no idea what lay ahead of me. All I knew was where I was staying. I had no idea how I would get there or how things would be when I got there. I knew that I would figure things out and eventually enjoy myself, but I couldn\'t help being a little nervous.');

day1.push('In the final section of the airport before the exit, I was overwhelmed. There were numerous car rental and taxi stands side by side, each with at least one employee yelling at everyone who passed by. Meanwhile more people were coming up to me and asking if I needed a taxi. I brushed everyone off and went to an ATM to take out some pesos. Appalled at the service fee of $33, I canceled my transaction and walked through the jungle to another one. I saw another backpacker taking out money there and asked her if there was a very large service fee. She said, "It\'s only about 30 pesos, it\'s not that bad." I laughed at myself for thinking it was in USD. I think all the noise and distraction disoriented me a little. Anyway, I weaved my way through the hallway and unfortunately it was no different outside. Tons of people would come up to me asking if I want a taxi, and I would reject them thinking that they would be heavily overpriced, especially because it was obvious I was a tourist. I tried to see if I could get to my hostel via bus with Google Maps, but nothing showed up. I was too freaked out to problem solve much more, so I eventually agreed to take a taxi. However, it was more of a van, and I had a feeling it would be extra pricey this way (however I didn\'t see any normal-sized taxis as options). On my way to the van the guy said the ride to my hostel would be $53 and I thought "Oh, that\'s not so bad." I waited in the van for the driver to come, meanwhile expecting a few more people to pour in, but I was on my own. The guy and the driver returned and said I had to pay up front. I took out 100 pesos and they said, "No, US dollars." I told them that was way too much, so he said we was willing to work with me, and so we settled on 500 pesos (about $27 USD), which is all I had taken out from the ATM. On the way to the hostel, I was upset that I hadn\'t tried to drive him further down, as I had already spent 3/4 of the maximum daily spending limit I had set for myself. However, I eventually just accepted it and calmed down.')

day1.push('I arrived at Hostel Quetzal. It was surrounded by a small beaten playground that they called a "park," and short, dirty buildings and walls. After entering, I had to pay the rest of my balance on my stay there, some 750 pesos. (Everything sounds way more expensive in pesos.) I put my stuff in my room and some valuables in a locker, then set out for a little stroll to an ATM. The lady\'s directions were not very good, but I was lucky enough to stumble upon another hostel where I asked someone how to get there.')

day1.push('The street that the supermarket was on was pretty cool - lots of shops, food and tourism stands along the way. I entered the supermarket and went to the ATMs on the left. There were 3 of them and for some reason almost everyone was lined up for one of them. I was worried about my choice of going to one with less of a line but knowing what I know now I think it was no different. I tried to be discreet in hiding the money I took out and cautiously walked through the supermarket being extremely vigilant and paranoid about protecting my valuables (I was thinking, "Crap! I should\'ve put on my money belt before leaving."). I grabbed a water then realized I was hungry. There was a little buffet thing there, with some options looking okay. However it was very confusing how it worked. I observed enough locals to realize where you pay, but I still didn\'t know how it worked with the buffet items. I saw a taco stand and walked over there but there was nobody behind the counter. I waited a bit to see if that would change, and once the lady showed up, so did a few customers, and the lady completely ignored me. I asked one of them how I was supposed to order the tacos, and he said to go to the cash register. After waiting in that line for a little, he came back to me and said I could actually order at the stand (even though it didn\'t seem so to me). So I went back, but he then talked with another customer and they agreed I actually did have to go to the cash register to order. Back in line for the register, I saw a local putting food from the buffet into containers I hadn\'t previously noticed, and I just decided to eat from there instead to avoid further potential issues. I ended up having a hot dog and pasta kind of thing, creamy greens, and rice. It wasn\'t half bad and only came out to about $3. The lady at the cash was nice, which I appreciated, and they accepted my credit card. There were only round tables to sit at, each with 6 or so chairs. I started off at my own table but then another local or two sat there as well. We\'d just exchange a simple "hola" then keep to ourselves eating our food. I thought it was pretty cool that there were no tables for groups of people of specific sizes - it seemed to have more of a community vibe to it.')

day1.push('I returned to the hostel to pay for the rest of my stay, then decided to walk around the place a little and see if get into some conversations. There were a few people in the family area not being overly inviting with their body language or glances, so I walked outside to take a picture of the setup. I briefly met a few people playing beer pong then went upstairs to see more. There I finally got into a better conversation. There were a few guys up there and we chatted for a while. There were nice and engaging and I felt more comfortable as I had some questions answered and we got to know each other. Then I met a nice couple chilling on the hammocks outside our rooms. I spent the rest of the day and night at the hostel, getting to know people and greatly enjoying the calming effect of the pool and the social vibe of the place as I increasingly felt more comfortable with my situation. It was a crazy feeling having it be my first night of a journey that could last a year.')

day1.push('The free dinner was a lovely perk of the place, and it was decent. After that, we all had a free shot together and played lots of drinking games. I was targeted for a while since it was my first night, but I handled it just fine. Eventually everyone drunkenly migrated to the pool and partied in there. The pool had a very interesting effect on everything. It felt like what I imagine it would feel like in the movie Avatar when they are all praying in unison by the holy tree. We all had an amazing time in there, playing chicken, dancing to blasting music, throwing each other around, etc. Needless to say, it was a good first day of my travels.')

day1.push('Oh, and to solidify the fact that I could not have high standards of living anymore, I had to sleep on a bed that two people had just had sex on. Luckily I had a sleep liner…')

export default day1